<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllAsArray($key, $dir) {
        return $this->createQueryBuilder('p')
        	->orderBy('p.'.$key, $dir)
            ->getQuery()
            ->getArrayResult();
    }
}
